config/routes.rb
Blog::Application.routes.draw do
  resources :feedbacks

  resources :time_allocates

  resources :eq_maintains

  get "search/index"

  resources :yy_informations

  get "admin/index"

  get "sessions/new"

  get "sessions/create"

  get "sessions/destroy"

  get 'admin'=>'admin#index'

  get 'search'=>'search#index'
  match 'articles/add/:id',:to=>'yy_informations#add',:as=>'add_yy_information'
  match 'articles/status_change/:id',:to=>'articles#status_change',:as=>'status_change_article'
  match 'articles/status_maintain',:to=>'articles#status_maintain',:as=>'status_maintain_article'
  match 'eq_maintains/add/:id',:to=>'eq_maintains#add',:as=>'add_eq_maintain'
  match 'time_allocates/add/:id',:to=>'time_allocates#add',:as=>'add_time_allocate'
  match 'time_allocates/lookup/:id',:to=>'time_allocates#lookup',:as=>'lookup_time_allocate'
  match 'time_allocates/personal_account/:id',:to=>'time_allocates#personal_account',:as=>'personal_account_time_allocate'
  match 'time_allocates/pay/:id',:to=>'time_allocates#pay',:as=>'pay_time_allocate'
  match 'feedbacks/add/:id',:to=>'feedbacks#add',:as=>'add_feedback'
  match 'yy_informations/status_change/:id',:to=>'yy_informations#status_change',:as=>'status_change_yy_information'
  post 'search'=>'articles#search'
  post'/search_status'=>'articles#search_status'
  controller :sessions do
    get 'login'=> :new
    post 'login'=> :create
    post 'sessions/new'=>:create
    get 'logout' =>:destroy
  end
  resources :users

  resources :articles

  get "home/index"

  root :to => "home#index"

end

app/models/yy_information.rb
class YyInformation < ActiveRecord::Base
end

app/controllers/yy_informations_controller.rb
class YyInformationsController < ApplicationController
  # GET /yy_informations
  # GET /yy_informations.json
  skip_before_filter :authorize
  def index
    @yy_informations = YyInformation.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @yy_informations }
    end
  end

  # GET /yy_informations/1
  # GET /yy_informations/1.json
  def show
    @yy_information = YyInformation.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @yy_information }
    end
  end

  # GET /yy_informations/new
  # GET /yy_informations/new.json
  def new
    @yy_information = YyInformation.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @yy_information }
    end
  end

  # GET /yy_informations/1/edit
  def edit
    @yy_information = YyInformation.find(params[:id])
  end
  def status_change
    @yy_information = YyInformation.find(params[:id])
  end
  def add
    #@yy_information = YyInformation.find(params[:id])
    @u = User.find_by_id(session[:user_id])
    @article = Article.find(params[:id])
    @yy_information = YyInformation.new
    @yy_information.eqdwid = @article.name
    @yy_information.eqname = @article.title
    @yy_information.eqid=@article.id
    @yy_information.pname =@u.name
    @yy_information.dw =@u.unitname
    @yy_information.email =@u.email
    @yy_information.phoneno =@u.phone
    @yy_information.save
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @yy_information }
    end
  end

  # POST /yy_informations
  # POST /yy_informations.json
  def create
    @yy_information = YyInformation.new(params[:yy_information])

    respond_to do |format|
      if @yy_information.save
        format.html { redirect_to @yy_information, notice: 'Yy information was successfully created.' }
        format.json { render json: @yy_information, status: :created, location: @yy_information }
     else
        format.html { render action: "new" }
        format.json { render json: @yy_information.errors, status: :unprocessable_entity }
      end
    end

  end

  # PUT /yy_informations/1
  # PUT /yy_informations/1.json
  def update
    @yy_information = YyInformation.find(params[:id])

    respond_to do |format|
      if @yy_information.update_attributes(params[:yy_information])
        format.html { redirect_to @yy_information, notice: 'Yy information was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @yy_information.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /yy_informations/1
  # DELETE /yy_informations/1.json
  def destroy
    @yy_information = YyInformation.find(params[:id])
    @yy_information.destroy

    respond_to do |format|
      format.html { redirect_to yy_informations_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/yy_informations_helper.rb
module YyInformationsHelper
end

app/views/yy_informations/_form.html.erb
<%= form_for(@yy_information) do |f| %>
  <% if @yy_information.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@yy_information.errors.count, "error") %> prohibited this yy_information from being saved:</h2>

      <ul>
      <% @yy_information.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <table style="width:100%">
      <tr>
        <td width="30%"><%= f.label :仪器编号 %></td>
        <td><%= f.text_field :eqid %></td>
      <tr>
      <tr>
        <td width="30%"><%= f.label :仪器所在单位 %></td>
        <td><%= f.text_field :eqdwid %></td>
      <tr>
      <tr>
        <td width="30%"><%= f.label :预约者姓名 %></td>
        <td><%= f.text_field :pname %></td>
      <tr>
      <tr>
        <td width="30%"><%= f.label :预约者所在单位 %></td>
        <td><%= f.text_field :dw %></td>
      <tr>
      <tr>
        <td width="30%"><%= f.label :预约者职务 %></td>
        <td><%= f.text_field :zw %></td>
      <tr>
      <tr>
        <td width="30%"><%= f.label :通讯地址 %></td>
        <td><%= f.text_field :addr %></td>
      <tr>
      <tr>
        <td width="30%"><%= f.label :邮政编码 %></td>
        <td><%= f.text_field :postno %></td>
      <tr>
      <tr>
        <td width="30%"><%= f.label :邮箱 %></td>
        <td><%= f.text_field :email %></td>
      <tr>
      <tr>
        <td width="30%"><%= f.label :联系电话 %></td>
        <td><%= f.text_field :phoneno %></td>
      <tr>
      <tr>
        <td width="30%"><%= f.label :使用目的 %></td>
        <td><%= f.text_area :symd , :rows=>5 %></td>
      <tr>
      <tr>
        <td width="30%"><%= f.label :使用要求 %></td>
        <td><%= f.text_area :syyq , :rows=>5 %></td>
      <tr>
      <tr>
        <td width="30%"><%= f.label :计划时间 %></td>
        <td><%= f.text_area :jhsj , :rows=>5 %></td>
      <tr>
      <tr>
        <td width="30%"><%= f.label :预约日期 %></td>
        <td><%= f.datetime_select :yyrq %></td>
      <tr>
      <tr>
        <td width="30%"><%= f.label :操作日期 %></td>
        <td><%= f.datetime_select :czrq %></td>
      <tr>
      <%if @u=User.find_by_id(session[:user_id])%>
        <%if @u.authority=='所级管理员'||@u.authority=='系统管理员'%>
              <tr>
                <td width="30%"><%= f.label :当前状态 %></td>
                <td>
                  <%= f.radio_button(:status, "未审核") %>
                  <%= label_tag(:status0, "未审核") %>
                  <%= f.radio_button(:status, "审核通过") %>
                  <%= label_tag(:status1, "审核通过") %>
                  <%= f.radio_button(:status, "已分配机时") %>
                  <%= label_tag(:status2, "已分配机时") %>
                  <%= f.radio_button(:status, "已使用") %>
                  <%= label_tag(:status2, "已使用") %>
                  <%= f.radio_button(:status, "已缴费") %>
                  <%= label_tag(:status3, "已缴费") %>
                </td>
              <tr>
            <%end%>
      <%end%>
    </table>
        <p> <%=submit_tag"预约确认" %> </p>
<% end %>

app/views/yy_informations/add.html.erb
<fieldset>
  <legend>新建预约</legend>
  <%= form_for(@yy_information) do |f| %>
      <% if @yy_information.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@yy_information.errors.count, "error") %> prohibited this yy_information from being saved:</h2>

            <ul>
              <% @yy_information.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
      <% end %>
      <table style="width:100%">
        <%if @article.status =='可预约'%>
        <tr>
          <td width="30%"><%= f.label :仪器编号 %></td>
          <td><%= @article.id %></td>
        <tr>
        <tr>
          <td width="30%"><%= f.label :仪器名称 %></td>
          <td><%= @article.title %></td>
        <tr>
        <tr>
          <td width="30%"><%= f.label :仪器所在单位 %></td>
          <td><%= @article.name %></td>
        <tr>
        <tr>
          <td width="30%"><%= f.label :预约者姓名 %></td>
          <td><%= @u.name %></td>
        <tr>
        <tr>
          <td width="30%"><%= f.label :预约者所在单位 %></td>
          <td><%= @u.unitname %></td>
        <tr>
        <tr>
          <td width="30%"><%= f.label :预约者职务 %></td>
          <td><%= f.text_field :zw %></td>
        <tr>
        <tr>
          <td width="30%"><%= f.label :通讯地址 %></td>
          <td><%= f.text_field :addr %></td>
        <tr>
        <tr>
          <td width="30%"><%= f.label :邮政编码 %></td>
          <td><%= f.text_field :postno %></td>
        <tr>
        <tr>
          <td width="30%"><%= f.label :邮箱 %></td>
          <td><%= @u.email %></td>
        <tr>
        <tr>
          <td width="30%"><%= f.label :联系电话 %></td>
          <td><%= @u.phone %></td>
        <tr>
        <tr>
          <td width="30%"><%= f.label :使用目的 %></td>
          <td><%= f.text_area :symd , :rows=>5 %></td>
        <tr>
        <tr>
          <td width="30%"><%= f.label :使用要求 %></td>
          <td><%= f.text_area :syyq , :rows=>5 %></td>
        <tr>
        <tr>
          <td width="30%"><%= f.label :计划时间 %></td>
          <td><%= f.text_area :jhsj , :rows=>5 %></td>
        <tr>
        <tr>
          <td width="30%"><%= f.label :预约日期 %></td>
          <td><%= f.datetime_select :yyrq %></td>
        <tr>
        <tr>
          <td width="30%"><%= f.label :操作日期 %></td>
          <td><%= f.datetime_select :czrq %></td>
        <tr>
      </table>
      <p> <%=submit_tag"预约确认" %> </p>
            <%= link_to '返回', yy_informations_path %>
        <% else %>
            <table>
            <tr>该仪器当前状态无法预约！<tr>
            </table>
            <%= link_to '返回', articles_url %>
        <% end %>
  <% end %>
</fieldset>

app/views/yy_informations/edit.html.erb
<fieldset>
  <legend>编辑预约</legend>
  <%= render 'form' %>
  <%= link_to '返回', yy_informations_path %>
</fieldset>

app/views/yy_informations/index.html.erb
<fieldset>
  <legend>预约列表</legend>

  <table style="width:100%" border="0">
    <tr>
    <th>预约编号</th>
    <th>仪器编号</th>
    <th>仪器名称</th>
    <th>预约者</th>
    <th>预约日期</th>
    <th>审核状态</th>
    <th></th>
    <th></th>
    <th></th>
      <th></th>
    </tr>
    <%@u=User.find_by_id(session[:user_id])%>
    <% @yy_informations.each do |yy_information| %>
        <%if @u.authority=='系统管理员'%>
            <tr>
              <td><%= yy_information.yyid %></td>
              <td><%= yy_information.eqid %></td>
              <td><%= yy_information.eqname %></td>
              <td><%= yy_information.pname %></td>
              <td><%= yy_information.yyrq %></td>
              <td><%= yy_information.status %></td>
              <td><%= link_to '编辑', edit_yy_information_path(yy_information) %></td>
              <td><%= button_to "删除", yy_information,:method=>:delete, :class=>:destroy %></td>
              <td><%= link_to '更改状态',status_change_yy_information_path(yy_information)%></td>
              <%if yy_information.status=='已分配机时'%>
                  <td><%= link_to '机时分配', add_time_allocate_path(yy_information) %></td>
              <% end %>
            </tr>
        <%end%>
        <% if @u.authority=='所级管理员'%>
                <%if yy_information.eqdwid == @u.unitname%>
                    <tr>
                      <td><%= yy_information.yyid %></td>
                      <td><%= yy_information.eqid %></td>
                      <td><%= yy_information.eqname %></td>
                      <td><%= yy_information.pname %></td>
                      <td><%= yy_information.yyrq %></td>
                      <td><%= yy_information.status %></td>
                      <td><%= link_to '查看', yy_information %></td>
                      <%if yy_information.status=='未审核'%>
                          <td><%= link_to '编辑', edit_yy_information_path(yy_information) %></td>
                          <td><%= button_to "删除", yy_information,:method=>:delete, :class=>:destroy %></td>
                      <%else%>
                          <td>审核通过不可修改</td>
                          <td><%= link_to '更改状态',status_change_yy_information_path(yy_information)%></td>
                          <%if yy_information.status=='已分配机时'%>
                          <td><%= link_to '机时分配', add_time_allocate_path(yy_information) %></td>
                          <% end %>
                      <% end %>
                    </tr>
                <%end%>
            <%end%>
        <% if  @u.authority=='普通用户'%>
            <%if yy_information.pname == @u.name%>
            <tr>
              <td><%= yy_information.yyid %></td>
              <td><%= yy_information.eqid %></td>
              <td><%= yy_information.eqname %></td>
              <td><%= yy_information.pname %></td>
              <td><%= yy_information.yyrq %></td>
              <td><%= yy_information.status %></td>
              <td><%= link_to '查看', yy_information %></td>
              <%if yy_information.status=='未审核'%>
                  <td><%= link_to '编辑', edit_yy_information_path(yy_information) %></td>
                  <td><%= button_to "删除", yy_information,:method=>:delete, :class=>:destroy %></td>
              <%else%>
                  <td>审核通过不可修改</td>
                  <%if yy_information.status=='已分配机时'||yy_information.status=='已使用'||yy_information.status=='已缴费'%>
                  <td><%= link_to '更改状态',status_change_yy_information_path(yy_information)%></td>
                  <% end %>
                  <%if yy_information.status=='已分配机时'%>
                  <td><%= link_to '查看机时分配', lookup_time_allocate_url(yy_information) %></td>
                  <% end %>
              <% end %>
            </tr>
            <% end %>
            <%end%>
    <% end %>
  </table>
</fieldset>

app/views/yy_informations/new.html.erb
<fieldset>
  <legend>新建预约</legend>
  <%= form_for(@yy_information) do |f| %>
      <% if @yy_information.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@yy_information.errors.count, "error") %> prohibited this yy_information from being saved:</h2>

            <ul>
              <% @yy_information.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
      <% end %>
      <table style="width:100%">
        <tr>
          <td width="30%"><%= f.label :仪器编号 %></td>
          <td><%= @article.id %></td>
        <tr>
        <tr>
          <td width="30%"><%= f.label :仪器名称 %></td>
          <td><%= @article.title %></td>
        <tr>
        <tr>
          <td width="30%"><%= f.label :仪器所在单位 %></td>
          <td><%= @article.name %></td>
        <tr>
        <tr>
          <td width="30%"><%= f.label :预约者姓名 %></td>
          <td><%= @u.name %></td>
        <tr>
        <tr>
          <td width="30%"><%= f.label :预约者所在单位 %></td>
          <td><%= @u.unitname %></td>
        <tr>
        <tr>
          <td width="30%"><%= f.label :预约者职务 %></td>
          <td><%= f.text_field :zw %></td>
        <tr>
        <tr>
          <td width="30%"><%= f.label :通讯地址 %></td>
          <td><%= f.text_field :addr %></td>
        <tr>
        <tr>
          <td width="30%"><%= f.label :邮政编码 %></td>
          <td><%= f.text_field :postno %></td>
        <tr>
        <tr>
          <td width="30%"><%= f.label :邮箱 %></td>
          <td><%= @u.email %></td>
        <tr>
        <tr>
          <td width="30%"><%= f.label :联系电话 %></td>
          <td><%= @u.phone %></td>
        <tr>
        <tr>
          <td width="30%"><%= f.label :使用目的 %></td>
          <td><%= f.text_area :symd , :rows=>5 %></td>
        <tr>
        <tr>
          <td width="30%"><%= f.label :使用要求 %></td>
          <td><%= f.text_area :syyq , :rows=>5 %></td>
        <tr>
        <tr>
          <td width="30%"><%= f.label :计划时间 %></td>
          <td><%= f.text_area :jhsj , :rows=>5 %></td>
        <tr>
        <tr>
          <td width="30%"><%= f.label :预约日期 %></td>
          <td><%= f.datetime_select :yyrq %></td>
        <tr>
        <tr>
          <td width="30%"><%= f.label :操作日期 %></td>
          <td><%= f.datetime_select :czrq %></td>
        <tr>
      </table>
      <p> <%=submit_tag"预约确认" %> </p>
  <% end %>
  <%= link_to '返回', yy_informations_path %>
</fieldset>

app/views/yy_informations/show.html.erb
<p id="notice"><%= notice %></p>
<fieldset>
  <legend>查看预约详细信息</legend>
<p>
  <b>预约编号:</b>
  <%= @yy_information.yyid %>
</p>

<p>
  <b>仪器编号:</b>
  <%= @yy_information.eqid %>
</p>
  <p>
    <b>仪器名称:</b>
    <%= @yy_information.eqname %>
  </p>
<p>
  <b>仪器所在单位:</b>
  <%= @yy_information.eqdwid %>
</p>

<p>
  <b>预约者姓名:</b>
  <%= @yy_information.pname %>
</p>

<p>
  <b>预约者所在单位:</b>
  <%= @yy_information.dw %>
</p>

<p>
  <b>预约者职务:</b>
  <%= @yy_information.zw %>
</p>

<p>
  <b>通讯地址:</b>
  <%= @yy_information.addr %>
</p>

<p>
  <b>邮政编码:</b>
  <%= @yy_information.postno %>
</p>

<p>
  <b>邮箱:</b>
  <%= @yy_information.email %>
</p>

<p>
  <b>联系电话:</b>
  <%= @yy_information.phoneno %>
</p>

<p>
  <b>使用目的:</b>
  <%= @yy_information.symd %>
</p>

<p>
  <b>使用要求:</b>
  <%= @yy_information.syyq %>
</p>

<p>
  <b>计划时间:</b>
  <%= @yy_information.jhsj %>
</p>

<p>
  <b>预约日期:</b>
  <%= @yy_information.yyrq %>
</p>

<p>
  <b>操作日期:</b>
  <%= @yy_information.czrq %>
</p>
  <p>
    <b>预约状态信息:</b>
    <%= @yy_information.status %>
  </p>
  <%if  @yy_information.status=='未审核'%>
  <%= link_to '编辑', edit_yy_information_path(@yy_information) %>
      <%end%>
<%= link_to '返回', yy_informations_path %>
</fieldset>

app/views/yy_informations/status_change.html.erb
<fieldset>
  <legend>编辑预约</legend>
  <%= form_for(@yy_information) do |f| %>
      <% if @yy_information.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@yy_information.errors.count, "error") %> prohibited this yy_information from being saved:</h2>

            <ul>
              <% @yy_information.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
      <% end %>
      <table style="width:100%">
        <tr>
          <td width="30%"><%= f.label :当前状态 %></td>
          <%@u=User.find_by_id(session[:user_id])%>
          <%if @u.authority!='普通用户'%>
          <td>
            <%= f.radio_button(:status, "未审核") %>
            <%= label_tag(:status0, "未审核") %>
            <%= f.radio_button(:status, "审核通过") %>
            <%= label_tag(:status1, "审核通过") %>
            <%= f.radio_button(:status, "已分配机时") %>
            <%= label_tag(:status2, "已分配机时") %>
            <%= f.radio_button(:status, "已使用") %>
            <%= label_tag(:status2, "已使用") %>
            <%= f.radio_button(:status, "已缴费") %>
            <%= label_tag(:status3, "已缴费") %>
          </td>
          <%else%>
              <td>
                <%= f.radio_button(:status, "已分配机时") %>
                <%= label_tag(:status2, "已分配机时") %>
                <%= f.radio_button(:status, "已使用") %>
                <%= label_tag(:status2, "已使用") %>
                <%= f.radio_button(:status, "已缴费") %>
                <%= label_tag(:status3, "已缴费") %>
              </td>
          <% end %>
        <tr>
      </table>
      <p> <%=submit_tag"状态更改确认" %> </p>
  <% end %>
  <%= link_to '返回', yy_informations_path %>
</fieldset>