config/routes.rb
Blog::Application.routes.draw do
  resources :feedbacks

  resources :time_allocates

  resources :eq_maintains

  get "search/index"

  resources :yy_informations

  get "admin/index"

  get "sessions/new"

  get "sessions/create"

  get "sessions/destroy"

  get 'admin'=>'admin#index'

  get 'search'=>'search#index'
  match 'articles/add/:id',:to=>'yy_informations#add',:as=>'add_yy_information'
  match 'articles/status_change/:id',:to=>'articles#status_change',:as=>'status_change_article'
  match 'articles/status_maintain',:to=>'articles#status_maintain',:as=>'status_maintain_article'
  match 'eq_maintains/add/:id',:to=>'eq_maintains#add',:as=>'add_eq_maintain'
  match 'time_allocates/add/:id',:to=>'time_allocates#add',:as=>'add_time_allocate'
  match 'time_allocates/lookup/:id',:to=>'time_allocates#lookup',:as=>'lookup_time_allocate'
  match 'time_allocates/personal_account/:id',:to=>'time_allocates#personal_account',:as=>'personal_account_time_allocate'
  match 'time_allocates/pay/:id',:to=>'time_allocates#pay',:as=>'pay_time_allocate'
  match 'feedbacks/add/:id',:to=>'feedbacks#add',:as=>'add_feedback'
  match 'yy_informations/status_change/:id',:to=>'yy_informations#status_change',:as=>'status_change_yy_information'
  post 'search'=>'articles#search'
  post'/search_status'=>'articles#search_status'
  controller :sessions do
    get 'login'=> :new
    post 'login'=> :create
    post 'sessions/new'=>:create
    get 'logout' =>:destroy
  end
  resources :users

  resources :articles

  get "home/index"

  root :to => "home#index"

end

app/models/article.rb
class Article < ActiveRecord::Base
end

app/controllers/articles_controller.rb
# encoding: utf-8
class ArticlesController < ApplicationController
  # GET /articles
  # GET /articles.xml
  skip_before_filter :authorize
  def status_maintain
    @articles = Article.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @articles }
      end
  end
  def index
    @articles = Article.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @articles }
    end
  end
  def status_change
    @article = Article.find(params[:id])
  end
  # GET /articles/1
  # GET /articles/1.xml
  def show
    @article = Article.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @article }
    end
  end

  # GET /articles/new
  # GET /articles/new.xml
  def new
    @article = Article.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @article }
    end
  end

  # GET /articles/1/edit
  def edit
    @article = Article.find(params[:id])
  end

  # POST /articles
  # POST /articles.xml
  def create
    @article = Article.new(params[:article])

    respond_to do |format|
      if @article.save
        format.html { redirect_to(@article, :notice => 'Article was successfully created.') }
        format.xml  { render :xml => @article, :status => :created, :location => @article }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @article.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /articles/1
  # PUT /articles/1.xml
  def update
    @article = Article.find(params[:id])

    respond_to do |format|
      if @article.update_attributes(params[:article])
        format.html { redirect_to(@article, :notice => 'Article was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @article.errors, :status => :unprocessable_entity }
      end
    end
  end
  def search
    searchName=params[:article][:title]
    case params[:search_type]
      when 'name'
        sql="select * from articles where title like '%"+searchName+"%'"
      when 'dw'
        sql="select * from articles where name like '%"+searchName+"%'"
      when 'eqspec'
        sql="select * from articles where eqspec like '%"+searchName+"%'"
      when 'status'
        sql="select * from articles where status like '%"+searchName+"%'"
      when 'type'
        sql="select * from articles where title like '%"+searchName+"%'"
    end
    @articles=Article.find_by_sql(sql)
    if @articles==nil
     #flash[:notice]="未找到相关设备"
    end
  end
  def search_status
    searchName=params[:article][:title]
    case params[:search_type]
      when 'name'
        sql="select * from articles where title like '%"+searchName+"%'"
      when 'dw'
        sql="select * from articles where name like '%"+searchName+"%'"
      when 'eqspec'
        sql="select * from articles where eqspec like '%"+searchName+"%'"
      when 'status'
        sql="select * from articles where status like '%"+searchName+"%'"
      when 'type'
        sql="select * from articles where title like '%"+searchName+"%'"
    end
    @articles=Article.find_by_sql(sql)
  end
  # DELETE /articles/1
  # DELETE /articles/1.xml
  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    respond_to do |format|
      format.html { redirect_to(articles_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
<% if @article.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>
  <ul>
    <% @article.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>
<table style="width:100%">
  <tr>
    <td width="30%"><%= f.label :仪器名称 %></td>
    <td><%= f.text_field :title %></td>
  <tr>
  <tr>
    <td width="30%"><%= f.label :仪器英文名称 %></td>
    <td><%= f.text_field :Englishname %></td>
  <tr>
  <tr>
    <td width="30%"><%= f.label :仪器所属研究单位 %></td>
    <td><%= f.text_field :name %></td>
  <tr>
  <tr>
    <td width="30%"><%= f.label :内容信息 %></td>
    <td><%= f.text_area :content, :rows=>5 %></td>
  <tr>
  <tr>
    <td width="30%"><%= f.label :仪器型号 %></td>
    <td><%= f.text_field :eqspec %></td>
  <tr>
  <tr>
    <td width="30%"><%= f.label :生产厂家 %></td>
    <td><%= f.text_field :eqcj %></td>
  <tr>
  <tr>
    <td width="30%"><%= f.label :生产日期 %></td>
    <td><%= f.date_select :eqdate_0 %></td>
  <tr>
  <tr>
    <td width="30%"><%= f.label :仪器总价 %></td>
    <td><%= f.text_field :eqvalue %></td>
  <tr>
  <tr>
    <td width="30%"><%= f.label :使用单位代码 %></td>
    <td><%= f.text_field :eqdwid %></td>
  <tr>
  <tr>
    <td width="30%"><%= f.label :管理人员 %></td>
    <td><%= f.text_field :eqm_person %></td>
  <tr>
  <tr>
    <td width="30%"><%= f.label :管理人员电话 %></td>
    <td><%= f.text_field :eqm_phone %></td>
  <tr>
  <tr>
    <td width="30%"><%= f.label :管理人员邮箱 %></td>
    <td><%= f.text_field :eq_email %></td>
  <tr>
  <tr>
    <td width="30%"><%= f.label :技术指标 %></td>
    <td><%= f.text_area :eqjszb , :rows=>5 %></td>
  <tr>
  <tr>
    <td width="30%"><%= f.label :功能特色 %></td>
    <td><%= f.text_area :eqgnts , :rows=>5 %></td>
  <tr>
  <tr>
    <td width="30%"><%= f.label :适用范围 %></td>
    <td><%= f.text_area :eqsyfw , :rows=>5 %></td>
  <tr>
  <tr>
    <td width="30%"><%= f.label :应用成果 %></td>
    <td><%= f.text_area :eqyycg , :rows=>5 %></td>
  <tr>
  <tr>
    <td width="30%"><%= f.label :提供服务 %></td>
    <td><%= f.text_area :eqtgfw , :rows=>5 %></td>
  <tr>
  <tr>
    <td width="30%"><%= f.label :收费标准 %></td>
    <td><%= f.text_area :eqsfbz , :rows=>5 %></td>
  <tr>
  <tr>
    <td width="30%"><%= f.label :可提供的机时 %></td>
    <td><%= f.text_field :eqkgjs %></td>
  <tr>
</table>
<p> <%= f.submit %> </p>
<% end %>

app/views/articles/edit.html.erb
<p> <%= link_to '返回查看', @article %> |<%= link_to '返回列表', articles_path %> </p>
<fieldset>
  <legend>编辑仪器信息</legend>
  <%= render 'form' %>
</fieldset>

app/views/articles/index.html.erb
<fieldset>
        <legend>仪器列表</legend>
<table style="width:100%" border="0">
  <tr>
    <th>编号</th>
    <th>仪器名称</th>
    <th>图片</th>
    <th>仪器所属研究单位</th>
    <th colspan="3">操作</th>
  </tr>
<% @articles.each do |article| %>
  <tr>
    <td><%= article.id %></td>
    <td><%= article.title %></td>
    <td><img width="60" height="70" src="<%= article.imageurl %>"/></td>
    <td><%= article.name %></td>
    <td><%= link_to '查看', article %></td>
    <%if @u=User.find_by_id(session[:user_id])%>
        <%if @u.authority=='所级管理员'||@u.authority=='系统管理员'%>
            <td><%= link_to '编辑', edit_article_path(article) %></td>
            <td><%= button_to "删除", article,:method=>:delete, :class=>:destroy %></td>
        <%else%>
            <td><%= link_to '预约',add_yy_information_path(article) %><td>
        <%end%>
    <%end%>
  </tr>
<% end %>
</table>
  <%if @u=User.find_by_id(session[:user_id])%>
      <%if @u.authority=='所级管理员'||@u.authority=='系统管理员'%>
  <p>
    <%= link_to '添加新的仪器', new_article_path %>
  </p>
          <%end%>
  <%end%>
</fieldset>

app/views/articles/new.html.erb
<p> <%= link_to '返回列表', articles_path %> </p>
<fieldset>
  <legend>添加新的仪器</legend>
  <%= render 'form' %>
</fieldset>

app/views/articles/search.html.erb
<fieldset>
  <legend>搜索结果</legend>
  <%=form_tag "/search" do %>
      搜索方式：
      <%= radio_button_tag(:search_type, "name") %>
      <%= label_tag(:age_child, "按仪器名称搜索") %>
      <%= radio_button_tag(:search_type, "dw") %>
      <%= label_tag(:age_adult, "按所在研究单位搜索") %>
      <%= radio_button_tag(:search_type, "eqspec") %>
      <%= label_tag(:age_adult, "按仪器型号搜索") %>
      <%= radio_button_tag(:search_type, "status") %>
      <%= label_tag(:age_adult, "按仪器状态搜索") %>
      <%= radio_button_tag(:search_type, "type") %>
      <%= label_tag(:age_adult, "按仪器类型搜索") %>
      <p>
        <%= text_field :article,:title,:style=>"margin-top:-10px" ,:size=>40 %>
        <%= submit_tag '给我搜' %>
  <% end %>
  </p>
  <table style="width:100%" border="0">
    <tr>
      <th>编号</th>
      <th>仪器名称</th>
      <th>图片</th>
      <th>仪器所属研究单位</th>
      <th colspan="3">操作</th>
    </tr>
    <% @articles.each do |article| %>
        <tr>
          <td><%= article.id %></td>
          <td><%= article.title %></td>
          <td><img width="60" height="70" src="<%= article.imageurl %>"/></td>
          <td><%= article.name %></td>
          <td><%= link_to '查看', article %></td>
          <%if @u=User.find_by_id(session[:user_id])%>
              <%if @u.authority=='所级管理员'||@u.authority=='系统管理员'%>
                  <td><%= link_to '编辑', edit_article_path(article) %></td>
                  <td><%= button_to "删除", article,:method=>:delete, :class=>:destroy %></td>
                  <%else%>
                  <td><%= link_to '预约',add_yy_information_path(article) %><td>
              <%end%>
          <%end%>
        </tr>
    <% end %>
    <%if @u=User.find_by_id(session[:user_id])%>
        <%if @u.authority=='所级管理员'||@u.authority=='系统管理员'%>
            <p>
              <%= link_to '添加新的仪器', new_article_path %>
            </p>
        <%end%>
    <%end%>
  </table>
</fieldset>

app/views/articles/search_status.html.erb
<fieldset>
  <legend>搜索结果123</legend>
  <%=form_tag "/search" do %>
      搜索方式：
      <%= radio_button_tag(:search_type, "name") %>
      <%= label_tag(:age_child, "按仪器名称搜索") %>
      <%= radio_button_tag(:search_type, "dw") %>
      <%= label_tag(:age_adult, "按所在研究单位搜索") %>
      <%= radio_button_tag(:search_type, "eqspec") %>
      <%= label_tag(:age_adult, "按仪器型号搜索") %>
      <%= radio_button_tag(:search_type, "status") %>
      <%= label_tag(:age_adult, "按仪器状态搜索") %>
      <%= radio_button_tag(:search_type, "type") %>
      <%= label_tag(:age_adult, "按仪器类型搜索") %>
      <p>
        <%= text_field :article,:title,:style=>"margin-top:-10px" ,:size=>40 %>
        <%= submit_tag '给我搜' %>
  <% end %>
  </p>
  <table style="width:100%" border="0">
    <tr>
      <th>编号</th>
      <th>仪器名称</th>
      <th>图片</th>
      <th>仪器所属研究单位</th>
      <th colspan="2">操作</th>
    </tr>
    <% @articles.each do |article| %>
        <tr>
          <td><%= article.id %></td>
          <td><%= article.title %></td>
          <td><img width="60" height="70" src="<%= article.imageurl %>"/></td>
          <td><%= article.name %></td>
          <td><%= link_to '查看', article %></td>
          <td><%= link_to '更改状态', status_change_article_path(article) %></td>
        </tr>
    <% end %>
  </table>
</fieldset>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>
<fieldset>
  <legend>查看仪器详细信息</legend>
  <br/>
  <h2> 仪器名称：<%= @article.title %></h2>
  <p> <b>English Name：</b> <%= @article.Englishname %> </p>
  <p> 编号：<%= @article.id %> | 仪器所属研究单位：<%= @article.name %> </p>
  <td><%=image_tag(@article.imageurl,:class => 'list_image')%></td>
  <p> 详细信息： <%= @article.content %> </p>
  <p> 仪器型号： <%= @article.eqspec %> </p>
  <p> 生产厂家： <%= @article.eqcj %> </p>
  <p> 生产日期： <%= @article.eqdate_0 %> </p>
  <p> 仪器总价： <%= @article.eqvalue %> </p>
  <p> 使用单位代码： <%= @article.eqdwid %> </p>
  <p> 管理人员： <%= @article.eqm_person %> </p>
  <p> 管理人员电话： <%= @article.eqm_phone %> </p>
  <p> 管理人员邮箱： <%= @article.eq_email %> </p>
  <p> 技术指标： <%= @article.eqjszb %> </p>
  <p> 功能特色： <%= @article.eqgnts %> </p>
  <p> 适用范围： <%= @article.eqsyfw %> </p>
  <p> 应用成果： <%= @article.eqyycg %> </p>
  <p> 提供服务： <%= @article.eqtgfw %> </p>
  <p> 收费标准： <%= @article.eqsfbz %> </p>
  <p> 当前状态： <%= @article.status %> </p>
  <p> 可提供的机时： <%= @article.eqkgjs %> </p>
  <p><%id=@article%></p>

  <%if @u=User.find_by_id(session[:user_id])%>
      <%if @u.authority=='所级管理员'||@u.authority=='系统管理员'%>
         <%= link_to '编辑', edit_article_path(@article) %>
      <%else %>
          <%= link_to '预约',add_yy_information_path(@article) %> |
      <%end%>
  <%end%>
  | <%= link_to '返回', articles_path %>
</fieldset>

app/views/articles/status_change.html.erb
<p> <%= link_to '返回查看', @article %> |<%= link_to '返回列表', articles_path %> </p>
<fieldset>
  <legend>编辑状态</legend>
  <%= form_for(@article) do |f| %>
      <% if @article.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>
            <ul>
              <% @article.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
      <% end %>
      <table style="width:100%">
        <tr>
          <td width="30%"><%= f.label :仪器名称 %></td>
          <td><%=@article.title%></td>
        <tr>
        <tr>
          <td width="30%"><%= f.label :仪器英文名称 %></td>
          <td><%=@article.Englishname%></td>
        <tr>
        <tr>
          <td width="30%"><%= f.label :仪器所属研究单位 %></td>
          <td><%=@article.name%></td>
        <tr>
        <tr>
          <td width="30%"><%= f.label :内容信息 %></td>
          <td><%=@article.content%></td>
        <tr>
        <tr>
          <td width="30%"><%= f.label :仪器型号 %></td>
          <td><%=@article.eqspec%></td>
        <tr>
        <tr>
          <td width="30%"><%= f.label :仪器状态 %></td>
          <td>
            <%= f.radio_button(:status, "可预约") %>
            <%= label_tag(:authority0, "可预约") %>
            <%= f.radio_button(:status, "正在使用") %>
            <%= label_tag(:authority1, "正在使用") %>
            <%= f.radio_button(:status, "维修中") %>
            <%= label_tag(:authority2, "维修中") %>
          </td>
        <tr>
        <tr>
          <td width="30%"><%= f.label :可提供的机时 %></td>
          <td><%= f.text_field :eqkgjs %></td>
        <tr>
      </table>
      <p> <%=submit_tag" 状态更改确认" %> </p>
  <% end %>

</fieldset>

app/views/articles/status_maintain.html.erb
<fieldset>
  <legend>仪器列表</legend>
  <%=form_tag "/search_status" do %>
      搜索方式：
      <%= radio_button_tag(:search_type, "name") %>
      <%= label_tag(:age_child, "按仪器名称搜索") %>
      <%= radio_button_tag(:search_type, "dw") %>
      <%= label_tag(:age_adult, "按所在研究单位搜索") %>
      <%= radio_button_tag(:search_type, "eqspec") %>
      <%= label_tag(:age_adult, "按仪器型号搜索") %>
      <%= radio_button_tag(:search_type, "status") %>
      <%= label_tag(:age_adult, "按仪器状态搜索") %>
      <%= radio_button_tag(:search_type, "type") %>
      <%= label_tag(:age_adult, "按仪器类型搜索") %>
      <p>
        <%= text_field :article,:title,:style=>"margin-top:-10px" ,:size=>40 %>
        <%= submit_tag '给我搜' %>
  <% end %>
  <table style="width:100%" border="0">
    <tr>
      <th>编号</th>
      <th>仪器名称</th>
      <th>图片</th>
      <th>仪器所属研究单位</th>
      <th colspan="3">操作</th>
    </tr>
    <% @articles.each do |article| %>
        <tr>
          <td><%= article.id %></td>
          <td><%= article.title %></td>
          <td><img width="60" height="70" src="<%= article.imageurl %>"/></td>
          <td><%= article.name %></td>
          <td><%= link_to '查看', article %></td>
          <td><%= link_to '更改状态', status_change_article_path(article) %></td>
          <%if article.status == '维修中'%>
              <td><%= link_to '填写维修记录', add_eq_maintain_path(article) %></td>
          <%end%>
        </tr>
    <% end %>
  </table>
</fieldset>