config/routes.rb
Blog::Application.routes.draw do
  resources :feedbacks

  resources :time_allocates

  resources :eq_maintains

  get "search/index"

  resources :yy_informations

  get "admin/index"

  get "sessions/new"

  get "sessions/create"

  get "sessions/destroy"

  get 'admin'=>'admin#index'

  get 'search'=>'search#index'
  match 'articles/add/:id',:to=>'yy_informations#add',:as=>'add_yy_information'
  match 'articles/status_change/:id',:to=>'articles#status_change',:as=>'status_change_article'
  match 'articles/status_maintain',:to=>'articles#status_maintain',:as=>'status_maintain_article'
  match 'eq_maintains/add/:id',:to=>'eq_maintains#add',:as=>'add_eq_maintain'
  match 'time_allocates/add/:id',:to=>'time_allocates#add',:as=>'add_time_allocate'
  match 'time_allocates/lookup/:id',:to=>'time_allocates#lookup',:as=>'lookup_time_allocate'
  match 'time_allocates/personal_account/:id',:to=>'time_allocates#personal_account',:as=>'personal_account_time_allocate'
  match 'time_allocates/pay/:id',:to=>'time_allocates#pay',:as=>'pay_time_allocate'
  match 'feedbacks/add/:id',:to=>'feedbacks#add',:as=>'add_feedback'
  match 'yy_informations/status_change/:id',:to=>'yy_informations#status_change',:as=>'status_change_yy_information'
  post 'search'=>'articles#search'
  post'/search_status'=>'articles#search_status'
  controller :sessions do
    get 'login'=> :new
    post 'login'=> :create
    post 'sessions/new'=>:create
    get 'logout' =>:destroy
  end
  resources :users

  resources :articles

  get "home/index"

  root :to => "home#index"

end

app/models/time_allocate.rb
class TimeAllocate < ActiveRecord::Base
end

app/controllers/time_allocates_controller.rb
# encoding: utf-8
class TimeAllocatesController < ApplicationController
  # GET /time_allocates
  # GET /time_allocates.json
  def index
    @time_allocates = TimeAllocate.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @time_allocates }
    end
  end

  # GET /time_allocates/1
  # GET /time_allocates/1.json
  def show
    @time_allocate = TimeAllocate.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @time_allocate }
    end
  end
  def personal_account
    @user = User.find(params[:id])
    searchName = @user.name
    sql="select * from time_allocates where user_name like '%"+searchName+"%'"
    @time_allocates=TimeAllocate.find_by_sql(sql)
    if @time_allocates==nil
      flash[:notice]="未找到相关设备"
    end
  end
  def add
    @yy_information = YyInformation.find(params[:id])
    @time_allocate = TimeAllocate.new
    @time_allocate.eqid=@yy_information.eqid
    @time_allocate.eqname=@yy_information.eqname
    @time_allocate.yyid=@yy_information.yyid
    @time_allocate.user_name=@yy_information.pname
    @time_allocate.eq_unitname=@yy_information.eqdwid
    @time_allocate.user_unitname=@yy_information.dw
    @time_allocate.save
  end
  def lookup
    @yy_information = YyInformation.find(params[:id])
    searchName=@yy_information.yyid
    sql="select * from time_allocates where yyid = "+searchName.to_s+""
    @time_allocates=TimeAllocate.find_by_sql(sql)
    if @time_allocates==nil
      flash[:notice]="未找到相关设备"
    end
  end
  # GET /time_allocates/new
  # GET /time_allocates/new.json
  def new
    @time_allocate = TimeAllocate.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @time_allocate }
    end
  end

  # GET /time_allocates/1/edit
  def edit
    @time_allocate = TimeAllocate.find(params[:id])
  end

  # POST /time_allocates
  # POST /time_allocates.json
  def create
    @time_allocate = TimeAllocate.new(params[:time_allocate])

    respond_to do |format|
      if @time_allocate.save
        format.html { redirect_to @time_allocate, notice: 'Time allocate was successfully created.' }
        format.json { render json: @time_allocate, status: :created, location: @time_allocate }
      else
        format.html { render action: "new" }
        format.json { render json: @time_allocate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /time_allocates/1
  # PUT /time_allocates/1.json
  def update
    @time_allocate = TimeAllocate.find(params[:id])

    respond_to do |format|
      if @time_allocate.update_attributes(params[:time_allocate])
        format.html { redirect_to @time_allocate, notice: 'Time allocate was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @time_allocate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /time_allocates/1
  # DELETE /time_allocates/1.json
  def destroy
    @time_allocate = TimeAllocate.find(params[:id])
    @time_allocate.destroy

    respond_to do |format|
      format.html { redirect_to time_allocates_url }
      format.json { head :no_content }
    end
  end
  def pay
    @time_allocate = TimeAllocate.find(params[:id])
  end
end

app/helpers/time_allocates_helper.rb
module TimeAllocatesHelper
end

app/views/time_allocates/_form.html.erb
<%= form_for(@time_allocate) do |f| %>
  <% if @time_allocate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@time_allocate.errors.count, "error") %> prohibited this time_allocate from being saved:</h2>

      <ul>
      <% @time_allocate.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :仪器编号 %><br />
    <%= f.text_field :eqid %>
  </div>
  <div class="field">
    <%= f.label :仪器名称 %><br />
    <%= f.text_field :eqname %>
  </div>
    <div class="field">
    <%= f.label :仪器所属单位 %><br />
    <%= f.text_field :eq_unitname %>
    </div>
  <div class="field">
    <%= f.label :预约编号 %><br />
    <%= f.text_field :yyid %>
  </div>
    <div class="field">
      <%= f.label :使用人 %><br />
      <%= f.text_field :user_name %>
    </div>
    <div class="field">
      <%= f.label :使用人单位 %><br />
      <%= f.text_field :user_unitname %>
    </div>
  <div class="field">
    <%= f.label :预约日期 %><br />
    <%= f.date_select :syrq %>
  </div>
    <div class="field">
      <%= f.label :时段选择 %><br />
      <%= f.time_select :start_time %>——
      <%= f.time_select :end_time %>
    </div>
    <div class="field">
      <%= f.label :总金额 %><br />
      <%= f.text_field :price %>
    </div>
    <div class="field">
      <%= f.label :状态 %><br />
      <%= f.radio_button(:status,"未分配") %>
      <%= f.label(:status, "未分配") %>
      <%= f.radio_button(:status,"未支付") %>
      <%= f.label(:status, "未支付") %>
      <%= f.radio_button(:status,"已支付") %>
      <%= f.label(:status, "已支付") %>
    </div>
    <div class="field">
      <%= f.label :备注 %><br />
      <%= f.text_field :bz %>
    </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/time_allocates/add.html.erb
<fieldset>
  <legend>填写时间分配记录</legend>
  <%= form_for(@time_allocate) do |f| %>
      <% if @time_allocate.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@time_allocate.errors.count, "error") %> prohibited this time_allocate from being saved:</h2>

            <ul>
              <% @time_allocate.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
      <% end %>

      <div class="field">
        <%= f.label :仪器编号 %>：
        <%= @yy_information.eqid %>
      </div>
      <div class="field">
        <%= f.label :仪器名称 %>：
        <%= @yy_information.eqname %>
      </div>
      <div class="field">
        <%= f.label :仪器所属单位 %>：
        <%= @yy_information.eqdwid %>
      </div>
      <div class="field">
        <%= f.label :预约编号 %>：
        <%= @yy_information.yyid %>
      </div>
      <div class="field">
        <%= f.label :使用人 %>：
        <%= @yy_information.pname %>
      </div>
      <div class="field">
        <%= f.label :使用人单位 %>：
        <%= @yy_information.dw %>
      </div>
      <div class="field">
        <%= f.label :使用时间 %><br />
        <%= f.date_select :syrq %>
      </div>
      <div class="field">
        <%= f.label :时段选择 %><br />
        <%= f.time_select :start_time %>——
        <%= f.time_select :end_time %>
      </div>
      <div class="field">
        <%= f.label :总金额 %><br />
        <%= f.text_field :price %>
      </div>
      <div class="field">
        <%= f.label :状态 %><br />
        <%= f.radio_button(:status,"未分配") %>
        <%= f.label(:status, "未分配") %>
        <%= f.radio_button(:status,"未支付") %>
        <%= f.label(:status, "未支付") %>
        <%= f.radio_button(:status,"已支付") %>
        <%= f.label(:status, "已支付") %>
      </div>
      <div class="field">
        <%= f.label :备注 %><br />
        <%= f.text_field :bz %>
      </div>
      <div class="actions">
        <%= f.submit %>
      </div>
  <% end %>
<%= link_to '查看', @time_allocate %> |
<%= link_to '退出', time_allocates_path %>
  </fieldset>

app/views/time_allocates/edit.html.erb
<fieldset>
  <legend>编辑时间分配记录</legend>
<%= render 'form' %>
  <%@u=User.find_by_id(session[:user_id])%>
<%= link_to '查看', @time_allocate %> |
  <%if @u.authority=='普通用户'%>
      <%= link_to '返回', yy_informations_url %>
  <%else%>
      <%= link_to '返回', time_allocates_url %>
  <%end%>
</fieldset>

app/views/time_allocates/index.html.erb
<fieldset>
  <legend>时间分配记录信息</legend>

  <table style="width:100%" border="0">
  <tr>
    <th>机时分配编号</th>
    <th>预约编号</th>
    <th>仪器名称</th>
    <th>仪器所属单位</th>
    <th>仪器编号</th>
    <th>使用人</th>
    <th>使用所属单位</th>
    <th>使用日期</th>
    <th>状态</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
    <%@u=User.find_by_id(session[:user_id])%>
<% @time_allocates.each do |time_allocate| %>
  <tr>
    <%if @u.authority == '所级管理员'%>
        <%if time_allocate.eq_unitname == @u.unitname &&@u.authority!='系统管理员'%>
            <td><%= time_allocate.id %></td>
            <td><%= time_allocate.yyid %></td>
            <td><%= time_allocate.eqname %></td>
            <td><%= time_allocate.eq_unitname %></td>
            <td><%= time_allocate.eqid %></td>
            <td><%= time_allocate.user_name %></td>
            <td><%= time_allocate.user_unitname %></td>
            <td><%= time_allocate.syrq %></td>
            <td><%= time_allocate.status %></td>
            <td><%= link_to '查看', time_allocate %></td>
            <td><%= link_to '编辑', edit_time_allocate_path(time_allocate) %></td>
            <td><%= button_to "删除", time_allocate,:method=>:delete, :class=>:destroy %></td>
        <%end%>
    <%end%>
    <%if @u.authority=='系统管理员'%>
        <td><%= time_allocate.id %></td>
        <td><%= time_allocate.yyid %></td>
        <td><%= time_allocate.eqname %></td>
        <td><%= time_allocate.eqid %></td>
        <td><%= time_allocate.user_name %></td>
        <td><%= time_allocate.syrq %></td>
        <td><%= time_allocate.status %></td>
        <td><%= link_to '查看', time_allocate %></td>
        <td><%= link_to '编辑', edit_time_allocate_path(time_allocate) %></td>
        <td><%= button_to "删除", time_allocate,:method=>:delete, :class=>:destroy %></td>
    <%end%>
  </tr>
<% end %>
</table>
<br />
  </fieldset>

app/views/time_allocates/lookup.html.erb
<fieldset>
  <legend>填写时间分配记录</legend>
  <p>查询记录为空表示尚未分配时间</p>
  <table style="width:100%" border="0">
    <tr>
      <th>机时分配编号</th>
      <th>预约编号</th>
      <th>仪器名称</th>
      <th>仪器所属单位</th>
      <th>仪器编号</th>
      <th>使用人</th>
      <th>使用所属单位</th>
      <th>使用日期</th>
      <th>状态</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
    <%@u=User.find_by_id(session[:user_id])%>
    <% @time_allocates.each do |time_allocate| %>
        <tr>
          <td><%= time_allocate.id %></td>
          <td><%= time_allocate.yyid %></td>
          <td><%= time_allocate.eqname %></td>
          <td><%= time_allocate.eq_unitname %></td>
          <td><%= time_allocate.eqid %></td>
          <td><%= time_allocate.user_name %></td>
          <td><%= time_allocate.user_unitname %></td>
          <td><%= time_allocate.syrq %></td>
          <td><%= time_allocate.status %></td>
          <td><%= link_to '查看', time_allocate %></td>

          <%if @u.authority=='所级管理员'||@u.authority=='系统管理员'%>
              <td><%= link_to '编辑', edit_time_allocate_path(time_allocate) %></td>
              <td><%= button_to "删除", time_allocate,:method=>:delete, :class=>:destroy %></td>
          <%end%>
          <%if @u.authority=='普通用户'%>
              <td><%= link_to '支付', edit_time_allocate_path(time_allocate) %></td>
          <%end%>
        </tr>
    <% end %>
  </table>
  <br />
</fieldset>

app/views/time_allocates/new.html.erb
<h1>New time_allocate</h1>

<%= render 'form' %>

<%= link_to 'Back', time_allocates_path %>

app/views/time_allocates/pay.html.erb
<fieldset>
  <legend>支付界面</legend>
  <%= form_for(@time_allocate) do |f| %>
      <% if @time_allocate.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@time_allocate.errors.count, "error") %> prohibited this time_allocate from being saved:</h2>

            <ul>
              <% @time_allocate.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
      <% end %>

      <div class="field">
        <%= f.label :仪器编号 %>：
        <%= @time_allocate.eqid %>
      </div>
      <div class="field">
        <%= f.label :仪器名称 %>：
        <%= @time_allocate.eqname %>
      </div>
      <div class="field">
        <%= f.label :仪器所属单位 %>：
        <%= @time_allocate.eq_unitname %>
      </div>
      <div class="field">
        <%= f.label :预约编号 %>：
        <%= @time_allocate.yyid %>
      </div>
      <div class="field">
        <%= f.label :使用人 %>：
        <%= @time_allocate.yyid %>
      </div>
      <div class="field">
        <%= f.label :使用人单位 %><br />
        <%= @time_allocate.user_unitname %>
      </div>
      <div class="field">
        <%= f.label :使用时间 %>：
        <%= @time_allocate.syrq %>
      </div>
      <div class="field">
        <%= f.label :使用时段 %>：
        <%= @time_allocate.start_time %>——
        <%= @time_allocate.end_time %>
      </div>
      <div class="field">
        <%= f.label :总金额 %>：
        <%=@time_allocate.price %>
      </div>
      <div class="field">
        <%= f.label :状态 %><br />
        <%= f.radio_button(:status,"未分配") %>
        <%= f.label(:status, "未分配") %>
        <%= f.radio_button(:status,"未支付") %>
        <%= f.label(:status, "未支付") %>
        <%= f.radio_button(:status,"已支付") %>
        <%= f.label(:status, "已支付") %>
      </div>
      <div class="field">
        <%= f.label :备注 %>：
        <%= @time_allocate.bz %>
      </div>
      <div class="actions">
        <%= f.submit %>
      </div>
  <% end %>
  <%= link_to '退出', home_index_path %>
</fieldset>

app/views/time_allocates/personal_account.html.erb
<fieldset>
  <legend>填写时间分配记录</legend>

  <table style="width:100%" border="0">
    <tr>
      <th>机时分配编号</th>
      <th>预约编号</th>
      <th>仪器名称</th>
      <th>仪器所属单位</th>
      <th>仪器编号</th>
      <th>使用人</th>
      <th>使用所属单位</th>
      <th>使用日期</th>
      <th>状态</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
    <%@u=User.find_by_id(session[:user_id])%>
    <% @time_allocates.each do |time_allocate| %>
        <tr>
          <td><%= time_allocate.id %></td>
          <td><%= time_allocate.yyid %></td>
          <td><%= time_allocate.eqname %></td>
          <td><%= time_allocate.eq_unitname %></td>
          <td><%= time_allocate.eqid %></td>
          <td><%= time_allocate.user_name %></td>
          <td><%= time_allocate.user_unitname %></td>
          <td><%= time_allocate.syrq %></td>
          <td><%= time_allocate.status %></td>
          <td><%= link_to '查看', time_allocate %></td>
          <%if @u.authority=='所级管理员'||@u.authority=='系统管理员'%>
              <td><%= link_to '编辑', edit_time_allocate_path(time_allocate) %></td>
              <td><%= button_to "删除", time_allocate,:method=>:delete, :class=>:destroy %></td>
          <%end%>
          <%if @u.authority=='普通用户'%>
          <%end%>
        </tr>
    <% end %>
  </table>
  <br />
</fieldset>

app/views/time_allocates/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <b>机时分配编号:</b>
  <%= @time_allocate.id %>
</p>
<p>
  <b>仪器编号:</b>
  <%= @time_allocate.eqid %>
</p>

<p>
  <b>仪器名称:</b>
  <%= @time_allocate.eqname %>
</p>
<p>
  <b>仪器所属单位:</b>
  <%= @time_allocate.eq_unitname %>
</p>
<p>
  <b>预约编号:</b>
  <%= @time_allocate.yyid %>
</p>
<p>
  <b>使用人:</b>
  <%= @time_allocate.yyid %>
</p>
<p>
  <b>使用人所属单位:</b>
  <%= @time_allocate.user_unitname %>
</p>
<p>
  <b>预约日期:</b>
  <%= @time_allocate.user_name %>
</p>
<p>
  <b>预约时段:</b>
  <%= @time_allocate.start_time %>——
  <%= @time_allocate.end_time %>
</p>
<p>
  <b>金额:</b>
  <%= @time_allocate.price %>
</p>

<p>
  <b>当前状态:</b>
  <%= @time_allocate.status %>
</p>
<p>
  <b>备注:</b>
  <%= @time_allocate.bz %>
</p>
<%@u=User.find_by_id(session[:user_id])%>
<%if @u.authority=='普通用户'%>
    <%= link_to '支付', pay_time_allocate_path(@time_allocate) %>
    <%= link_to '返回', yy_informations_url %>
    <%else%>
    <%= link_to '编辑', edit_time_allocate_path(@time_allocate) %> |
    <%= link_to '返回', time_allocates_url %>
<%end%>