config/routes.rb
Blog::Application.routes.draw do
  resources :feedbacks

  resources :time_allocates

  resources :eq_maintains

  get "search/index"

  resources :yy_informations

  get "admin/index"

  get "sessions/new"

  get "sessions/create"

  get "sessions/destroy"

  get 'admin'=>'admin#index'

  get 'search'=>'search#index'
  match 'articles/add/:id',:to=>'yy_informations#add',:as=>'add_yy_information'
  match 'articles/status_change/:id',:to=>'articles#status_change',:as=>'status_change_article'
  match 'articles/status_maintain',:to=>'articles#status_maintain',:as=>'status_maintain_article'
  match 'eq_maintains/add/:id',:to=>'eq_maintains#add',:as=>'add_eq_maintain'
  match 'time_allocates/add/:id',:to=>'time_allocates#add',:as=>'add_time_allocate'
  match 'time_allocates/lookup/:id',:to=>'time_allocates#lookup',:as=>'lookup_time_allocate'
  match 'time_allocates/personal_account/:id',:to=>'time_allocates#personal_account',:as=>'personal_account_time_allocate'
  match 'time_allocates/pay/:id',:to=>'time_allocates#pay',:as=>'pay_time_allocate'
  match 'feedbacks/add/:id',:to=>'feedbacks#add',:as=>'add_feedback'
  match 'yy_informations/status_change/:id',:to=>'yy_informations#status_change',:as=>'status_change_yy_information'
  post 'search'=>'articles#search'
  post'/search_status'=>'articles#search_status'
  controller :sessions do
    get 'login'=> :new
    post 'login'=> :create
    post 'sessions/new'=>:create
    get 'logout' =>:destroy
  end
  resources :users

  resources :articles

  get "home/index"

  root :to => "home#index"

end

app/models/article.rb
class Article < ActiveRecord::Base
end

app/models/eq_maintain.rb
class EqMaintain < ActiveRecord::Base
end

app/models/feedback.rb
class Feedback < ActiveRecord::Base
end

app/models/time_allocate.rb
class TimeAllocate < ActiveRecord::Base
end

app/models/user.rb
require 'digest/sha2'
class User < ActiveRecord::Base
  validates :name, :presence => true, :uniqueness => false
  validates :logname, :presence => true, :uniqueness => true
  validates :password, :confirmation => true
  attr_accessor :password_confirmation
  attr_reader :password
  validate :password_must_be_present
  def User.authenticate(logname,password)
    if user = find_by_logname(logname)
      if user.hashed_password == encrypt_password(password,user.salt)
        user
      end
    end
  end
  def User.encrypt_password(password,salt)
    Digest::SHA2.hexdigest(password+"wibble"+salt)
  end
  def password=(password)
    @password = password

    if password.present?
      generate_salt
      self.hashed_password = self.class.encrypt_password(password,salt)
    end
  end
  private
  def password_must_be_present
    errors.add(:password,"Missing password") unless hashed_password.present?
  end
  def generate_salt
    self.salt=self.object_id.to_s+rand.to_s
  end
end

app/models/yy_information.rb
class YyInformation < ActiveRecord::Base
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  skip_before_filter :authorize
  def index
   # @total_order =Order.count
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_filter :authorize
  def index
  end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  skip_before_filter :authorize
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  skip_before_filter :authorize
  def index
    @users = User.order(:name)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to(home_index_url ,:notice => "User #{@user.name} was successfully created.")}
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to(home_index_url ,:notice => "User #{@user.name} was successfully created.") }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/eq_maintains_helper.rb
module EqMaintainsHelper
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/time_allocates_helper.rb
module TimeAllocatesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/index.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>图片平滑切换</title>
  <%= javascript_include_tag "jquery-1.7.2.min.js"%>
  <%= stylesheet_link_tag "admin" %>
</head>
<body>
<div class="main">
  <div id="container">
    <ul class="image">
      <li><%= image_tag "bing-1.jpg" %></li>
      <li><%= image_tag "bing-3.jpg" %></li>
      <li><%= image_tag "bing-4.jpg" %></li>
      <li><%= image_tag "bing-5.jpg" %></li>

    </ul>
    <ul class="sign">
      <li class="on">1</li>
      <li>2</li>
      <li>3</li>
      <li>4</li>

    </ul>
  </div>

</div>

<script type="text/javascript" charset="utf-8">
    $(function () {
        var len = $(".image > li").length;   //元素个数
        var i = 0;
        function turn() {
            i = $(".sign li").index($(".on"))  //获取当前种子标识
            i < len - 1 ? i++ : i = 0   //循环切换
            $(".sign li").eq(i).addClass("on").siblings("li").removeClass("on");  //高亮
            showImg(i);  //切换图片
        }
        $(".sign > li").click(function () {
            clearInterval(set);   //清除定时器
            var index = $(this).index();
            $(this).addClass("on").siblings("li").removeClass("on");
            showImg(index);
            set = setInterval(turn, 5000);
        });
        set = setInterval(turn, 5000);
    });

    function showImg(index) {
        var width = $("#container").width();
        $(".image").stop(true, false).animate({ "left": -index * width }, 500);
    }
</script>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <link rel="stylesheet" type="text/css" href="/stylesheets/style.css" media="screen" />
  <%= javascript_include_tag "jquery.min.js"%>

  <meta http-equiv="content-type" content="text/html; charset=utf-8" />
  <title>中国科学院大型仪器设备共享平台</title>
</head>
<body>
<style type="text/css">
    *{padding:0;margin:0;outline:none;}
    body{font-family:'MicroSoft Yahei',verdana,arial,tahoma;font-size:12px;color:#333;-webkit-text-size-adjust: none;}
    ul,ol,dd{list-style:none}
    a{text-decoration:none;word-wrap:break-word;outline:none;hide-focus:expression(this.hideFocus=true);transition:all 0.2s ease-in-out;-webkit-transition:all 0.2s ease-in-out;-moz-transition:all 0.2s ease-in-out;-o-transition:all 0.2s ease-in-out;-ms-transition:all 0.2s ease-in-out;}
    a:hover{text-decoration:none;}

    /* lanmu-content */
    .lanmu-content{width:160px;margin:40px auto 0 auto;float:left;}
    .lanmu-content .listmore{display:block;text-align:center;height:25px;border-top:0;background:#eee;color:#1594d1;font:normal 12px/25px Tahoma,Verdana;}
    .lanmu-list{display:block;}
    .lanmu-list dt{display:block;height:40px;background:#0066CC;font:bold 14px/40px "宋体"; color:#fff;padding-left:10px;}
    .lanmu-list dd{padding-top:2px;}
    .lanmu-list dd a{display:block;height:33px;background:#D5DBD2;border-bottom:1px solid #eee;border-top:2px solid #fff;border-left:2px solid #999;border-right:1px solid #eee;font:normal 12px/33px Georgia "宋体"; color:#696969;padding-left:25px; line-height: 33px;}
    .lanmu-list dd a:hover{padding-left:35px;}
    .lanmu-list dd a:hover,.lanmu-list dd a.current{border-left:2px solid #1160ba;background-color:#f6f6f6;color:#1160ba;font-weight:bold;}
</style>

<div class="page_wrap clearfix">

  <div class="top"></div>

  <div class="header" >

  </div>

  <div class="container clearfix">

    <div class="lanmu-content">
      <dl class="lanmu-list">
        <%if @u=User.find_by_id(session[:user_id])%>

            <li>您好！<%= @u.name%></li>
            <li>您的角色是<%= @u.authority%></li>
            <%if @u.authority == '普通用户'%>
                <dt>预约系统</dt>
                <dd><%= link_to "首页", home_index_path %></dd>
                <dd><%= link_to "仪器搜索", search_index_path%></dd>
                <dd><%= link_to "仪器列表", articles_url %></dd>
                <dd><%= link_to "个人预约", yy_informations_url %></dd>
                <dd><%= link_to "个人账单", personal_account_time_allocate_path(@u) %></dd>
                <dd><%= link_to "信息反馈", feedbacks_path %></dd>

                <dd><%= link_to "个人注册信息修改", edit_user_path(@u) %></dd>
                <dd><%= link_to "退出登录", logout_path, :method=>:delete%></dd>
            <%end%>
            <%if @u.authority == '所级管理员'%>
                <dt>预约系统</dt>
                <dd><%= link_to "首页", home_index_path %></dd>
                <dd><%= link_to "仪器搜索", search_index_path %></dd>
                <dd><%= link_to "仪器列表", articles_url %></dd>
                <dt>维护系统</dt>
                <dd><%= link_to "设备状态维护", status_maintain_article_path %></dd>
                <dd><%= link_to "预约处理", yy_informations_url %></dd>
                <dd><%= link_to "设备借用手续办理", time_allocates_url %></dd>
                <dd><%= link_to "设备维护信息", eq_maintains_path %></dd>
                <dd><%= link_to "院系账号管理", users_url %></dd>
                <dd><%= link_to "反馈信息管理", feedbacks_path %></dd>

                <dd><%= link_to "退出登录", logout_path, :method=>:delete%></dd>
            <%end%>
            <%if @u.authority == '系统管理员'%>
                <dd><%= link_to "首页", home_index_path %></dd>

                <dt>维护系统</dt>
                <dd><%= link_to "设备状态维护", status_maintain_article_path %></dd>
                <dd><%= link_to "预约处理", yy_informations_url %></dd>
                <dd><%= link_to "设备借用手续办理", time_allocates_url %></dd>
                <dd><%= link_to "设备维护信息", eq_maintains_path %></dd>
                <dt>后台管理</dt>
                <dd><%= link_to "仪器搜索", search_index_path %></dd>
                <dd><%= link_to "设备管理", articles_url %></dd>
                <dd><%= link_to "费用管理", home_index_path %></dd>
                <dd><%= link_to "数据统计", home_index_path %></dd>
                <dd><%= link_to "账号管理", users_url %></dd>
                <dd><%= link_to "系统维护", home_index_path %></dd>

                <dd><%= link_to "退出登录", logout_path, :method=>:delete%></dd>
            <%end%>
        <%else%>
            <dd><%= link_to "用户登录", login_url %></dd>
            <dd><%= link_to "用户注册", new_user_path %></dd>
        <%end%>

      </dl>
    </div>

    <%= yield %>
  </div>

  <div class="bottom clearfix">
    <div class="footer clearfix"> Copyright, UCAS，SDM &nbsp;&#8226;&nbsp; Design
      by Mr Walnut </div>
  </div>
</div>
</body>
</html>